E2Helper.Descriptions["tanktracktoolCanUseValue()"] = "Checks the calm down whenever a value can be used"
E2Helper.Descriptions["tanktracktoolCopyValues(e:e)"] = "Copies the track values from one entity to another"
E2Helper.Descriptions["tanktracktoolResetValues(e:)"] = "Resets the entity internal track values"
E2Helper.Descriptions["tanktracktoolSetLinks(e:t)"] = "Updates the entity links from the table passed"
E2Helper.Descriptions["tanktracktoolCreate(nssva)"] = "Create an entity with given class by request"
E2Helper.Descriptions["tanktracktoolGetLinkNames(e:)"] = "Returns an array containing the link names"
E2Helper.Descriptions["tanktracktoolSetValue(e:s...)"] = "Updates the values under the specified index"
